---

- hosts: [server3]
  become: true
  tasks:
  - name: Download zabbix-agent CentOS 7
    yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-latest.el7.noarch.rpm
    when:
        ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  - name: Install zabbix-agent CentOS 7
    yum:
        name=zabbix-agent
        state=present
  - name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
  - name: Download postgresql-12 CentOS 7
    yum:
      name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    when:
        ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  - name: Install postgresql-12 CentOS 7
    yum:
        name=postgresql12-server
        state=present
  - name: Start postgresql12-server
    service:
      name: postgresql-12
      state: stopped
      enabled: yes
