---

- hosts: [server2]
  become: true
  tasks:
  - name: Install Nginx Ubuntu 20
    apt:
        name=nginx
        state=latest

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Install Apache Ubuntu
    apt:
        name=apache2
        state=latest
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Install PHP
    apt:
        name=php
        state=latest
  - name: Install PHP-fpm
    apt:
        name=php-fpm
        state=latest
  - name: Install libapache2-mod-php
    apt:
        name=libapache2-mod-php
        state=latest
  - name: Install bind9
    apt:
        name=bind9
        state=latest
  - name: Start bind9
    service:
      name: bind9
      state: started
      enabled: yes
  - name: Install Dovecot
    apt:
        name=dovecot-core
        state=latest
  - name: Install Dovecot
    apt:
        name=dovecot-imapd
        state=latest
  - name: Install Dovecot
    apt:
        name=dovecot-pop3d
        state=latest
  - name: Install Dovecot
    apt:
        name=dovecot-lmtpd
        state=latest

  - name: Start dovecot
    service:
      name: dovecot
      state: started
      enabled: yes



