---

- hosts: [servers]
  become: true
  tasks:

  - name: Get Hostname
    shell: hostname
    register: result_hostname

  - name: Install zabbix release Ubuntu 20
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu20.04_all.deb

    when:
       ansible_os_family == "Debian"

  - name: Install zabbix-release CentOS 7
    yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/7/x86_64/zabbix-release-latest.el7.noarch.rpm
    when:
        ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install zabbix-agent
    yum: name=zabbix-agent
         state=present

    when:
        ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"



  - name: Install zabbix-agent on Ubuntu 20
    apt:
        name=zabbix-agent
        state=present
    when:
       ansible_os_family == "Debian"

  - name: Change Server IP
    lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        line: "Server=10.0.0.1"

  - name: Change Active Server IP
    lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive=127.0.0.1'
        line: "ServerActive=10.0.0.1"

  - name: Change hostname
    lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '# Hostname='
        line: "Hostname={{ result_hostname.stdout }}"

  - name: Stop zabbix-agent
    service:
        name: zabbix-agent
        state: stopped
        enabled: no
    ignore_errors: yes

  - name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
